# Generated by Django 4.0.3 on 2022-04-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog_tea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tea',
            new_name='is_tea',
        ),
    ]
