# Generated by Django 4.0.3 on 2022-04-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pscord', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
